# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc81cd2788710790449485cc440d4df164209299a439b81ab83bbcaa78ec038fcfea3b5547f7bde8f4b9adec82ba6086b824b1eac2d1b9859f6137a17279dc14

test:
  secret_key_base: 57e94437aeb3ee50b55c8fb8facf532992ca2eff1df99b214ea9b40462476ca4e0cf254eaee5349d8d7f1f64b1df4d40712bc54cbc487734a3312ef869972a06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
